# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-06 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('enunciado', models.CharField(max_length=50)),
                ('opcion1', models.CharField(max_length=20)),
                ('opcion2', models.CharField(max_length=20)),
                ('opcion3', models.CharField(max_length=20)),
                ('opcion4', models.CharField(max_length=20)),
                ('referencia_dia_opcion_1', models.CharField(choices=[('0', 'Ninguno'), ('1', 'Viernes'), ('2', 'Sabado'), ('3', 'Domingo'), ('4', 'Combo')], max_length=1)),
                ('referencia_artista_opcion_1', models.CharField(choices=[('-', 'Ninguno'), ('TK', 'The Killers'), ('G', 'Gorillaz'), ('LDR', 'Lana Del Rey'), ('LCD', 'LCD Soundsystem'), ('DJ', 'DJ Snake')], max_length=3)),
                ('referencia_dia_opcion_2', models.CharField(choices=[('0', 'Ninguno'), ('1', 'Viernes'), ('2', 'Sabado'), ('3', 'Domingo'), ('4', 'Combo')], max_length=1)),
                ('referencia_artista_opcion_2', models.CharField(choices=[('-', 'Ninguno'), ('TK', 'The Killers'), ('G', 'Gorillaz'), ('LDR', 'Lana Del Rey'), ('LCD', 'LCD Soundsystem'), ('DJ', 'DJ Snake')], max_length=3)),
                ('referencia_dia_opcion_3', models.CharField(choices=[('0', 'Ninguno'), ('1', 'Viernes'), ('2', 'Sabado'), ('3', 'Domingo'), ('4', 'Combo')], max_length=1)),
                ('referencia_artista_opcion_3', models.CharField(choices=[('-', 'Ninguno'), ('TK', 'The Killers'), ('G', 'Gorillaz'), ('LDR', 'Lana Del Rey'), ('LCD', 'LCD Soundsystem'), ('DJ', 'DJ Snake')], max_length=3)),
                ('referencia_dia_opcion_4', models.CharField(choices=[('0', 'Ninguno'), ('1', 'Viernes'), ('2', 'Sabado'), ('3', 'Domingo'), ('4', 'Combo')], max_length=1)),
                ('referencia_artista_opcion_4', models.CharField(choices=[('-', 'Ninguno'), ('TK', 'The Killers'), ('G', 'Gorillaz'), ('LDR', 'Lana Del Rey'), ('LCD', 'LCD Soundsystem'), ('DJ', 'DJ Snake')], max_length=3)),
            ],
        ),
    ]
